version: '3.8'
services:
  avd_tester:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
  db:
      container_name: postgres-container
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: avd
        PGDATA: /data/postgres
      ports:
        - "5432:5432"
      volumes:
        - /Volumes:/var/lib/postgresql/data
volumes:
  pg_data: