version: '3.8'
services:
  avd_tester:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
  db:
      container_name: postgres-container
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: avd
        PGDATA: /data/postgres
      ports:
        - "5432:5432"
      volumes:
        - /Volumes:/var/lib/postgresql/data
  metabase-app:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      - /home/app/metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: avd
      MB_DB_PORT: 5432
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: db
      MB_DB_FILE: /metabase-data/metabase.db

    depends_on:
      - db
    links:
      - db 
volumes:
  pg_data: